project:
  type: website
  output-dir: ../docs

  resources:
    - Attie500_Liver_Lipids.html
    - QTLretrievR.html

render:
  - index.qmd
  - QTLretrievR_embed.qmd
  - Attie500_Liver_embed.qmd


website:
  title: "QTLretrievR"
  navbar:
    title: false
    logo: qtlretrievr_hex.png
    left:
      - href: index.qmd
        text: Home
      - text: Articles
        menu:
          - text: Get Started
            href: QTLretrievR_embed.html
          - text: QTL (200 Phenotypes)
            href: Attie500_Liver_embed.html

format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true

