project:
  type: website
  output-dir: ../docs

  resources:
    - articles/Attie500_Liver_Lipids_ref.html
    - articles/QTLretrievR_ref.html
    - qtlretrievr_hex.png
    - styles.css

render:
  - index.qmd
  - QTLretrievR.qmd
  - Attie500_Liver_Lipids.qmd


website:
  title: "QTLretrievR"
  navbar:
    title: false
    logo: qtlretrievr_hex.png
    left:
      - href: index.qmd
        text: Home
      - text: Articles
        menu:
          - text: Get Started
            href: QTLretrievR.html
          - text: QTL (200 Phenotypes)
            href: Attie500_Liver_Lipids.html

format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true

